# syntax=docker/dockerfile:1
FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    libcairo2 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-bot.txt .

RUN pip install uv && rm -rf ~/.cache/pip

RUN --mount=type=cache,target=/root/.cache/uv \
    uv pip install --system -r requirements-bot.txt

COPY . .

CMD ["python", "-m", "src.telegram.bot"]
