ALTER TABLE lesson_plans
ADD COLUMN IF NOT EXISTS periods JSON DEFAULT NULL,
ADD COLUMN IF NOT EXISTS exit_ticket JSON DEFAULT NULL,
ADD COLUMN IF NOT EXISTS differentiation JSON DEFAULT NULL,
ADD COLUMN IF NOT EXISTS diagram_suggestions JSON DEFAULT NULL,
ADD COLUMN IF NOT EXISTS misconception_activities JSON DEFAULT NULL;
