ALTER TABLE student_mastery
ADD COLUMN IF NOT EXISTS subject VARCHAR(20) DEFAULT NULL;

ALTER TABLE progress_records
ADD COLUMN IF NOT EXISTS subject VARCHAR(20) DEFAULT NULL;

ALTER TABLE student_abilities
ADD COLUMN IF NOT EXISTS subject VARCHAR(20) DEFAULT NULL;

ALTER TABLE quizzes
ADD COLUMN IF NOT EXISTS subject VARCHAR(20) DEFAULT NULL;
