# ruff: noqa: E501

KNOWN_MISCONCEPTIONS = [
    # Cell Biology
    {
        "topic": "Cell Biology",
        "misconception": "All cells are the same size",
        "explanation": "Cells vary greatly in size depending on their function and type. For example, nerve cells can be over a meter long while red blood cells are microscopic.",
        "severity": "misunderstanding",
        "related_objectives": ["Cell structure", "Cell diversity"],
        "recommended_strategies": ["Comparison diagram", "Microscope observation"],
        "detection_patterns": ["cells are all the same", "every cell is", "all cells have same"],
        "grade_level": 9,
    },
    {
        "topic": "Cell Biology",
        "misconception": "Mitosis produces four daughter cells",
        "explanation": "Mitosis produces two genetically identical daughter cells. Meiosis produces four genetically different daughter cells.",
        "severity": "misconception",
        "related_objectives": ["Cell division", "Mitosis stages", "Meiosis"],
        "recommended_strategies": ["Comparison diagram", "Stage sequencing activity"],
        "detection_patterns": ["mitosis produces 4", "mitosis makes four", "mitosis results in 4"],
        "grade_level": 10,
    },
    {
        "topic": "Cell Biology",
        "misconception": "Plant cells do not have mitochondria",
        "explanation": "Plant cells do have mitochondria. They perform cellular respiration just like animal cells, in addition to photosynthesis in chloroplasts.",
        "severity": "misconception",
        "related_objectives": ["Cell organelles", "Cellular respiration", "Photosynthesis"],
        "recommended_strategies": ["Labeled diagram", "Venn diagram comparison"],
        "detection_patterns": [
            "plants don't have mitochondria",
            "plant cells lack mitochondria",
            "no mitochondria in plants",
        ],
        "grade_level": 9,
    },
    {
        "topic": "Cell Biology",
        "misconception": "The nucleus is the brain of the cell and controls everything independently",
        "explanation": "While the nucleus contains genetic material and directs many cell activities, cellular processes involve complex interactions between all organelles. No single organelle works alone.",
        "severity": "misunderstanding",
        "related_objectives": ["Nucleus function", "Organelle interactions"],
        "recommended_strategies": ["Systems thinking exercise", "Organelle role-play"],
        "detection_patterns": ["nucleus is the brain", "nucleus controls everything"],
        "grade_level": 9,
    },
    # Genetics
    {
        "topic": "Genetics",
        "misconception": "Genes only exist in reproductive cells",
        "explanation": "Genes exist in every cell of the body. Every nucleated cell contains the full genome. Only some genes are expressed in each cell type.",
        "severity": "misconception",
        "related_objectives": ["Gene expression", "DNA location", "Cell differentiation"],
        "recommended_strategies": ["Concept mapping", "Gene expression simulation"],
        "detection_patterns": [
            "genes only in reproductive",
            "genes only in sex cells",
            "only gametes have genes",
        ],
        "grade_level": 10,
    },
    {
        "topic": "Genetics",
        "misconception": "Dominant genes are always the most common in a population",
        "explanation": "Dominance refers to which trait is expressed when different alleles are present, not how common an allele is in a population. A recessive allele can be more common.",
        "severity": "misunderstanding",
        "related_objectives": ["Dominant vs recessive", "Allele frequency", "Population genetics"],
        "recommended_strategies": ["Punnett square practice", "Population example analysis"],
        "detection_patterns": [
            "dominant is more common",
            "dominant means more frequent",
            "dominant allele is common",
        ],
        "grade_level": 10,
    },
    {
        "topic": "Genetics",
        "misconception": "Mutations are always harmful",
        "explanation": "Mutations can be harmful, neutral, or beneficial. They are the original source of genetic variation that drives evolution.",
        "severity": "misunderstanding",
        "related_objectives": ["Mutation types", "Genetic variation", "Evolution"],
        "recommended_strategies": ["Mutation case studies", "Beneficial mutation examples"],
        "detection_patterns": [
            "mutations are always bad",
            "all mutations are harmful",
            "mutation is always negative",
        ],
        "grade_level": 10,
    },
    {
        "topic": "Genetics",
        "misconception": "A child inherits more DNA from the parent they resemble most",
        "explanation": "A child inherits exactly 50% of their DNA from each parent. Physical resemblance to one parent does not mean they inherited more DNA from that parent.",
        "severity": "knowledge_gap",
        "related_objectives": ["Inheritance patterns", "DNA transmission"],
        "recommended_strategies": ["Pedigree analysis", "Inheritance simulation"],
        "detection_patterns": ["inherits more from", "more DNA from", "resembles more so more DNA"],
        "grade_level": 10,
    },
    # Evolution
    {
        "topic": "Evolution",
        "misconception": "Humans evolved from monkeys",
        "explanation": "Humans and modern monkeys share a common ancestor that lived millions of years ago. Humans did not evolve from monkeys; both lineages diverged from a common ancestor.",
        "severity": "misconception",
        "related_objectives": ["Common ancestry", "Evolutionary trees", "Hominid evolution"],
        "recommended_strategies": ["Phylogenetic tree analysis", "Timeline comparison"],
        "detection_patterns": [
            "humans evolved from monkeys",
            "humans came from apes",
            "evolved from monkeys",
        ],
        "grade_level": 10,
    },
    {
        "topic": "Evolution",
        "misconception": "Evolution is a linear progression toward more complex organisms",
        "explanation": "Evolution does not have a direction or goal. It is a branching process driven by natural selection in response to environmental pressures.",
        "severity": "misconception",
        "related_objectives": ["Natural selection", "Adaptation", "Evolutionary theory"],
        "recommended_strategies": ["Branching tree exercise", "Adaptation case studies"],
        "detection_patterns": [
            "evolution progresses",
            "evolution moves toward",
            "evolution is linear",
            "more complex over time",
        ],
        "grade_level": 10,
    },
    {
        "topic": "Evolution",
        "misconception": "Individual organisms can evolve during their lifetime",
        "explanation": "Evolution occurs at the population level over generations. Individual organisms do not evolve; they adapt through physiological changes.",
        "severity": "misconception",
        "related_objectives": ["Natural selection mechanism", "Population genetics"],
        "recommended_strategies": ["Generation simulation", "Population vs individual comparison"],
        "detection_patterns": [
            "individual can evolve",
            "organisms evolve during",
            "evolve in their lifetime",
            "adapt and evolve the same",
        ],
        "grade_level": 10,
    },
    # Cellular Respiration & Photosynthesis
    {
        "topic": "Cellular Respiration",
        "misconception": "Respiration only occurs in lungs",
        "explanation": "Respiration has two meanings: breathing (ventilation) and cellular respiration. Cellular respiration occurs in the mitochondria of every living cell.",
        "severity": "persistent_misconception",
        "related_objectives": ["Cellular respiration", "Gas exchange", "Mitochondria function"],
        "recommended_strategies": ["Concept conflict activity", "Two-meanings exercise"],
        "detection_patterns": [
            "respiration only in lungs",
            "respiration happens in lungs",
            "breathing is respiration",
        ],
        "grade_level": 9,
    },
    {
        "topic": "Photosynthesis",
        "misconception": "Plants only perform photosynthesis, not respiration",
        "explanation": "Plants perform both photosynthesis and cellular respiration. During the day they do both; at night they continue respiration using stored energy.",
        "severity": "persistent_misconception",
        "related_objectives": ["Photosynthesis", "Cellular respiration", "Plant metabolism"],
        "recommended_strategies": ["24-hour cycle diagram", "Experiment evidence"],
        "detection_patterns": [
            "plants only photosynthesize",
            "plants don't respire",
            "plants only do photosynthesis",
        ],
        "grade_level": 9,
    },
    {
        "topic": "Photosynthesis",
        "misconception": "Plants get their food from the soil",
        "explanation": "Plants produce their own food through photosynthesis using sunlight, water, and carbon dioxide. Soil provides minerals and water but not energy-rich food molecules.",
        "severity": "misunderstanding",
        "related_objectives": ["Photosynthesis process", "Plant nutrition", "Autotrophs"],
        "recommended_strategies": [
            "Historical experiment demonstration",
            "Mass experiment analysis",
        ],
        "detection_patterns": [
            "plants get food from soil",
            "plants eat soil",
            "food comes from soil",
        ],
        "grade_level": 9,
    },
    # Human Biology
    {
        "topic": "Human Biology",
        "misconception": "Blood in arteries is always oxygenated",
        "explanation": "Pulmonary arteries carry deoxygenated blood from the heart to the lungs. Only systemic arteries carry oxygenated blood. The naming is based on direction, not oxygen content.",
        "severity": "misunderstanding",
        "related_objectives": ["Circulatory system", "Heart function", "Gas exchange"],
        "recommended_strategies": ["Circulation pathway diagram", "Color-coding exercise"],
        "detection_patterns": [
            "arteries always carry oxygen",
            "all arteries have oxygenated",
            "arteries carry only oxygen",
        ],
        "grade_level": 10,
    },
    {
        "topic": "Human Biology",
        "misconception": "The brain uses 10% of its capacity",
        "explanation": "This is a myth. Brain imaging shows that different regions are active at different times, but over a day nearly all parts of the brain are used.",
        "severity": "knowledge_gap",
        "related_objectives": ["Brain structure", "Brain function"],
        "recommended_strategies": ["Brain imaging analysis", "Myth-busting activity"],
        "detection_patterns": ["brain uses 10%", "only 10% of brain", "10 percent of brain"],
        "grade_level": 10,
    },
    {
        "topic": "Human Biology",
        "misconception": "Different parts of the tongue detect different basic tastes exclusively",
        "explanation": "The tongue map is a myth. All taste buds can detect all five basic tastes (sweet, sour, salty, bitter, umami), though some regions have different sensitivities.",
        "severity": "knowledge_gap",
        "related_objectives": ["Taste perception", "Sensory receptors"],
        "recommended_strategies": ["Taste experiment", "Myth-busting comparison"],
        "detection_patterns": [
            "tongue map",
            "different parts of tongue taste",
            "sweet taste bud location",
        ],
        "grade_level": 9,
    },
    # Ecology
    {
        "topic": "Ecology",
        "misconception": "An organism's habitat and niche are the same thing",
        "explanation": "A habitat is where an organism lives (its address). A niche is its role in the ecosystem including what it eats, what eats it, and how it interacts (its profession).",
        "severity": "misunderstanding",
        "related_objectives": ["Ecological concepts", "Habitat vs niche", "Ecosystem interactions"],
        "recommended_strategies": ["Address vs profession analogy", "Niche analysis activity"],
        "detection_patterns": [
            "habitat and niche are same",
            "habitat is the same as niche",
            "niche equals habitat",
        ],
        "grade_level": 9,
    },
    {
        "topic": "Ecology",
        "misconception": "If a predator is removed, prey populations will grow indefinitely",
        "explanation": "Removing predators can lead to prey population increases, but other limiting factors (food, disease, space) will eventually control the population.",
        "severity": "misunderstanding",
        "related_objectives": ["Population dynamics", "Carrying capacity", "Ecosystem balance"],
        "recommended_strategies": ["Population simulation", "Case study analysis"],
        "detection_patterns": [
            "prey will grow forever",
            "without predators prey unlimited",
            "remove predators prey explodes",
        ],
        "grade_level": 10,
    },
    {
        "topic": "Ecology",
        "misconception": "Energy is recycled in ecosystems",
        "explanation": "Energy flows through ecosystems in one direction (sun to producers to consumers to decomposers) and is lost as heat at each trophic level. Matter is recycled, not energy.",
        "severity": "misconception",
        "related_objectives": ["Energy flow", "Trophic levels", "Nutrient cycling"],
        "recommended_strategies": ["Energy pyramid construction", "Flow vs cycle diagram"],
        "detection_patterns": [
            "energy is recycled",
            "energy gets reused",
            "energy cycles in ecosystem",
        ],
        "grade_level": 10,
    },
]

MISCONCEPTION_SEVERITIES = {
    "knowledge_gap": {
        "label": "Knowledge Gap",
        "rank": 1,
        "description": "Student lacks information",
    },
    "misunderstanding": {
        "label": "Misunderstanding",
        "rank": 2,
        "description": "Partial understanding with gaps",
    },
    "misconception": {"label": "Misconception", "rank": 3, "description": "Incorrect mental model"},
    "persistent_misconception": {
        "label": "Persistent Misconception",
        "rank": 4,
        "description": "Repeated over time, highest severity",
    },
}
